apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
  - port: 8081
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  selector:
    matchLabels:
        app: jenkins
  template:
    metadata:
        labels:
            app: jenkins
    spec:
      containers:
        - name: jenkins
          image: berwoutv/jenkins:latest
          ports:
          - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /login
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
          - name: jenkins-pv-storage
            mountPath: "/var/jenkins_home"
          - name: docker-socket
            mountPath: "/var/run/docker.sock"
      volumes:
        - name: jenkins-pv-storage
          persistentVolumeClaim:
            claimName: jenkins-pv-claim
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
            type: File
---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: jenkins
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: deploy-to-jenkins
subjects:
    - kind: ServiceAccount
      name: jenkins
roleRef:
    kind: Role
    name: cluster-admin
    apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi